const { Router } = require("express");
const { search } = require("../controllers/searchController");
const { db } = require("../db/config");

const router = Router();

router.get("/", search);
router.get("/addUsers", (req, res) => {
  db.insert({
    table: "users",
    records: [
      {
        email: "عسل.مرادی@example.com",
        gender: "female",
        phone_number: "0925-326-2063",
        birthdate: 417058382,
        location: {
          street: "4981 شهید بهشتی",
          city: "پاکدشت",
          state: "مرکزی",
          postcode: 68555,
        },
        username: "ticklishfish813",
        password: "zaq12wsx",
        first_name: "عسل",
        last_name: "مرادی",
        title: "mrs",
        picture: "women/65.jpg",
      },
      {
        email: "باران.یاسمی@example.com",
        gender: "female",
        phone_number: "0908-264-0594",
        birthdate: 1095446730,
        location: {
          street: "3192 دکتر مفتح",
          city: "پاکدشت",
          state: "خوزستان",
          postcode: 28471,
        },
        username: "ticklishfrog180",
        password: "satan666",
        first_name: "باران",
        last_name: "یاسمی",
        title: "ms",
        picture: "women/21.jpg",
      },
      {
        email: "noah.poulsen@example.com",
        gender: "male",
        phone_number: "53705244",
        birthdate: 1314124015,
        location: {
          street: "7998 oddenvej",
          city: "nr åby",
          state: "syddanmark",
          postcode: 73617,
        },
        username: "purplesnake503",
        password: "zelda",
        first_name: "noah",
        last_name: "poulsen",
        title: "mr",
        picture: "men/41.jpg",
      },
      {
        email: "priteche.fogaça@example.com",
        gender: "male",
        phone_number: "(57) 6145-5813",
        birthdate: 625120148,
        location: {
          street: "1857 rua rio de janeiro ",
          city: "jaboatão dos guararapes",
          state: "rio grande do norte",
          postcode: 70353,
        },
        username: "yellowkoala267",
        password: "jabber",
        first_name: "priteche",
        last_name: "fogaça",
        title: "mr",
        picture: "algolia/men/gabe.png",
      },
      {
        email: "edgar.friedrich@example.com",
        gender: "male",
        phone_number: "0174-6711492",
        birthdate: 286791690,
        location: {
          street: "4728 mittelstraße",
          city: "trier",
          state: "thüringen",
          postcode: 99400,
        },
        username: "purplebear225",
        password: "maddie",
        first_name: "edgar",
        last_name: "friedrich",
        title: "mr",
        picture: "men/70.jpg",
      },
      {
        email: "benjamin.beck@example.com",
        gender: "male",
        phone_number: "0459-316-814",
        birthdate: 113060175,
        location: {
          street: "426 central st",
          city: "sunshine coast",
          state: "tasmania",
          postcode: 6859,
        },
        username: "ticklishrabbit361",
        password: "bergkamp",
        first_name: "benjamin",
        last_name: "beck",
        title: "mr",
        picture: "men/61.jpg",
      },
      {
        email: "sofie.sørensen@example.com",
        gender: "female",
        phone_number: "75873392",
        birthdate: 551033950,
        location: {
          street: "5116 jagtvej",
          city: "frederiksberg",
          state: "hovedstaden",
          postcode: 72840,
        },
        username: "heavymeercat516",
        password: "trick",
        first_name: "sofie",
        last_name: "sørensen",
        title: "ms",
        picture: "women/4.jpg",
      },
      {
        email: "alizee.leroux@example.com",
        gender: "female",
        phone_number: "06-89-25-69-04",
        birthdate: 674256103,
        location: {
          street: "3379 avenue debrousse",
          city: "reims",
          state: "vienne",
          postcode: 88218,
        },
        username: "brownmeercat168",
        password: "turtle",
        first_name: "alizee",
        last_name: "leroux",
        title: "ms",
        picture: "women/83.jpg",
      },
      {
        email: "sheryl.carr@example.com",
        gender: "female",
        phone_number: "0731-134-689",
        birthdate: 117923501,
        location: {
          street: "8570 queens road",
          city: "aberdeen",
          state: "county armagh",
          postcode: "OM3F 9YU",
        },
        username: "redbear154",
        password: "ziggy",
        first_name: "sheryl",
        last_name: "carr",
        title: "ms",
        picture: "women/75.jpg",
      },
      {
        email: "emeline.charles@example.com",
        gender: "female",
        phone_number: "(311)-279-7621",
        birthdate: 22755420,
        location: {
          street: "9655 rue paul-duvivier",
          city: "romanel-sur-lausanne",
          state: "aargau",
          postcode: 7949,
        },
        username: "heavyfish951",
        password: "karen",
        first_name: "emeline",
        last_name: "charles",
        title: "mademoiselle",
        picture: "women/90.jpg",
      },
      {
        email: "ariana.thompson@example.com",
        gender: "female",
        phone_number: "(403)-255-8521",
        birthdate: 508616445,
        location: {
          street: "2962 esmonde road",
          city: "christchurch",
          state: "northland",
          postcode: 90291,
        },
        username: "brownostrich745",
        password: "hungry",
        first_name: "ariana",
        last_name: "thompson",
        title: "ms",
        picture: "women/52.jpg",
      },
      {
        email: "jeremy.weiss@example.com",
        gender: "male",
        phone_number: "0172-9704083",
        birthdate: 1097265312,
        location: {
          street: "3704 ringstraße",
          city: "lüchow-dannenberg",
          state: "bremen",
          postcode: 10531,
        },
        username: "blackbird279",
        password: "mone",
        first_name: "jeremy",
        last_name: "weiss",
        title: "mr",
        picture: "men/37.jpg",
      },
      {
        email: "marcos.soto@example.com",
        gender: "male",
        phone_number: "685-327-108",
        birthdate: 867726469,
        location: {
          street: "9443 avenida del planetario",
          city: "alcobendas",
          state: "canarias",
          postcode: 58149,
        },
        username: "heavygoose114",
        password: "roll",
        first_name: "marcos",
        last_name: "soto",
        title: "mr",
        picture: "men/31.jpg",
      },
      {
        email: "sofia.sales@example.com",
        gender: "female",
        phone_number: "(69) 6275-4624",
        birthdate: 841700488,
        location: {
          street: "3688 rua joão xxiii",
          city: "catanduva",
          state: "piauí",
          postcode: 26830,
        },
        username: "redlion952",
        password: "kaiser",
        first_name: "sofia",
        last_name: "sales",
        title: "ms",
        picture: "women/66.jpg",
      },
      {
        email: "anna.miller@example.com",
        gender: "female",
        phone_number: "0757-774-062",
        birthdate: 1378090803,
        location: {
          street: "3577 chester road",
          city: "ely",
          state: "berkshire",
          postcode: "W9 1BP",
        },
        username: "orangemouse723",
        password: "siobhan",
        first_name: "anna",
        last_name: "miller",
        title: "miss",
        picture: "women/84.jpg",
      },
      {
        email: "donald.riley@example.com",
        gender: "male",
        phone_number: "(804)-650-8144",
        birthdate: 759024694,
        location: {
          street: "5828 first street",
          city: "dumas",
          state: "nevada",
          postcode: 61505,
        },
        username: "browngoose143",
        password: "clevelan",
        first_name: "donald",
        last_name: "riley",
        title: "mr",
        picture: "men/34.jpg",
      },
      {
        email: "melany.wijngaard@example.com",
        gender: "female",
        phone_number: "(727)-033-9347",
        birthdate: 608022796,
        location: {
          street: "2431 predikherenkerkhof",
          city: "staphorst",
          state: "gelderland",
          postcode: 64265,
        },
        username: "bigpeacock217",
        password: "eagle",
        first_name: "melany",
        last_name: "wijngaard",
        title: "miss",
        picture: "women/70.jpg",
      },
      {
        email: "mathias.nielsen@example.com",
        gender: "male",
        phone_number: "10676217",
        birthdate: 609178245,
        location: {
          street: "6304 spættevej",
          city: "århus c.",
          state: "hovedstaden",
          postcode: 21472,
        },
        username: "beautifulbutterfly247",
        password: "336699",
        first_name: "mathias",
        last_name: "nielsen",
        title: "mr",
        picture: "men/14.jpg",
      },
      {
        email: "claire.garcia@example.com",
        gender: "female",
        phone_number: "(358)-286-2903",
        birthdate: 513865716,
        location: {
          street: "5695 avenue debourg",
          city: "bournens",
          state: "schaffhausen",
          postcode: 1210,
        },
        username: "redelephant795",
        password: "showing",
        first_name: "claire",
        last_name: "garcia",
        title: "madame",
        picture: "women/81.jpg",
      },
      {
        email: "ashley.tucker@example.com",
        gender: "female",
        phone_number: "081-346-8038",
        birthdate: 206529207,
        location: {
          street: "3693 west street",
          city: "listowel",
          state: "nevada",
          postcode: 62963,
        },
        username: "organicfrog467",
        password: "feet",
        first_name: "ashley",
        last_name: "tucker",
        title: "ms",
        picture: "women/47.jpg",
      },
      {
        email: "alyssa.andre@example.com",
        gender: "female",
        phone_number: "06-61-26-48-78",
        birthdate: 14471564,
        location: {
          street: "4392 place du 22 novembre 1943",
          city: "mulhouse",
          state: "lozère",
          postcode: 33786,
        },
        username: "bigtiger239",
        password: "clover",
        first_name: "alyssa",
        last_name: "andre",
        title: "mrs",
        picture: "women/37.jpg",
      },
      {
        email: "summer.wood@example.com",
        gender: "female",
        phone_number: "(631)-847-8482",
        birthdate: 541808639,
        location: {
          street: "8538 fitzherbert avenue",
          city: "palmerston north",
          state: "bay of plenty",
          postcode: 24035,
        },
        username: "purpleleopard272",
        password: "malice",
        first_name: "summer",
        last_name: "wood",
        title: "mrs",
        picture: "women/34.jpg",
      },
      {
        email: "natércio.castro@example.com",
        gender: "male",
        phone_number: "(24) 9586-4164",
        birthdate: 175528223,
        location: {
          street: "2970 rua vinte e dois ",
          city: "olinda",
          state: "sergipe",
          postcode: 18053,
        },
        username: "purplewolf989",
        password: "blanca",
        first_name: "natércio",
        last_name: "castro",
        title: "mr",
        picture: "men/13.jpg",
      },
      {
        email: "terrence.king@example.com",
        gender: "male",
        phone_number: "0446-337-253",
        birthdate: 971665235,
        location: {
          street: "7435 first street",
          city: "australian capital territory",
          state: "south australia",
          postcode: 9658,
        },
        username: "organickoala820",
        password: "cwoui",
        first_name: "terrence",
        last_name: "king",
        title: "mr",
        picture: "men/87.jpg",
      },
      {
        email: "william.david@example.com",
        gender: "male",
        phone_number: "(494)-541-3062",
        birthdate: 498456350,
        location: {
          street: "1507 rue abel-ferry",
          city: "aclens",
          state: "schaffhausen",
          postcode: 4583,
        },
        username: "orangepanda797",
        password: "pinkfloyd",
        first_name: "william",
        last_name: "david",
        title: "monsieur",
        picture: "men/38.jpg",
      },
      {
        email: "irene.morales@example.com",
        gender: "female",
        phone_number: "625-790-958",
        birthdate: 513983644,
        location: {
          street: "4096 calle del arenal",
          city: "lorca",
          state: "castilla y león",
          postcode: 40542,
        },
        username: "goldenfish109",
        password: "field",
        first_name: "irene",
        last_name: "morales",
        title: "mrs",
        picture: "women/87.jpg",
      },
      {
        email: "آرمیتا.سلطانینژاد@example.com",
        gender: "female",
        phone_number: "0904-946-2757",
        birthdate: 1282460030,
        location: {
          street: "5379 شیخ فضل الله نوری",
          city: "زنجان",
          state: "آذربایجان غربی",
          postcode: 67937,
        },
        username: "blueswan165",
        password: "nudes",
        first_name: "آرمیتا",
        last_name: "سلطانی نژاد",
        title: "mrs",
        picture: "women/8.jpg",
      },
      {
        email: "stefan.siebert@example.com",
        gender: "male",
        phone_number: "0175-8081099",
        birthdate: 995242988,
        location: {
          street: "9925 römerstraße",
          city: "kleve",
          state: "saarland",
          postcode: 93927,
        },
        username: "crazycat938",
        password: "sommer",
        first_name: "stefan",
        last_name: "siebert",
        title: "mr",
        picture: "men/21.jpg",
      },
      {
        email: "amy.miller@example.com",
        gender: "female",
        phone_number: "567-629-4636",
        birthdate: 487837819,
        location: {
          street: "2206 grand marais ave",
          city: "st. antoine",
          state: "saskatchewan",
          postcode: 83344,
        },
        username: "bluebear787",
        password: "soft",
        first_name: "amy",
        last_name: "miller",
        title: "miss",
        picture: "women/58.jpg",
      },
      {
        email: "noélie.roux@example.com",
        gender: "female",
        phone_number: "06-68-19-42-68",
        birthdate: 669873438,
        location: {
          street: "6224 rue barrème",
          city: "paris",
          state: "ain",
          postcode: 89564,
        },
        username: "blueelephant373",
        password: "282828",
        first_name: "noélie",
        last_name: "roux",
        title: "mrs",
        picture: "women/51.jpg",
      },
      {
        email: "enrique.brewer@example.com",
        gender: "male",
        phone_number: "081-445-2504",
        birthdate: 777104132,
        location: {
          street: "1252 church street",
          city: "newcastle west",
          state: "arkansas",
          postcode: 28056,
        },
        username: "heavywolf560",
        password: "deaths",
        first_name: "enrique",
        last_name: "brewer",
        title: "mr",
        picture: "men/76.jpg",
      },
      {
        email: "abssilão.rodrigues@example.com",
        gender: "male",
        phone_number: "(12) 1563-0822",
        birthdate: 12543906,
        location: {
          street: "2358 rua são luiz ",
          city: "pinhais",
          state: "amapá",
          postcode: 62771,
        },
        username: "smallleopard973",
        password: "emerson",
        first_name: "abssilão",
        last_name: "rodrigues",
        title: "mr",
        picture: "men/5.jpg",
      },
      {
        email: "liam.walters@example.com",
        gender: "male",
        phone_number: "0438-376-652",
        birthdate: 826530877,
        location: {
          street: "9156 dogwood ave",
          city: "devonport",
          state: "australian capital territory",
          postcode: 7374,
        },
        username: "biglion964",
        password: "training",
        first_name: "liam",
        last_name: "walters",
        title: "mr",
        picture: "men/50.jpg",
      },
      {
        email: "nicole.curtis@example.com",
        gender: "female",
        phone_number: "081-784-8292",
        birthdate: 1154981509,
        location: {
          street: "9640 denny street",
          city: "carrick-on-suir",
          state: "missouri",
          postcode: 83944,
        },
        username: "goldenbutterfly133",
        password: "tunafish",
        first_name: "nicole",
        last_name: "curtis",
        title: "mrs",
        picture: "women/41.jpg",
      },
      {
        email: "deolindo.vieira@example.com",
        gender: "male",
        phone_number: "(93) 2134-8962",
        birthdate: 1116215145,
        location: {
          street: "6274 rua santa maria ",
          city: "varginha",
          state: "rondônia",
          postcode: 78801,
        },
        username: "bigsnake641",
        password: "darklord",
        first_name: "deolindo",
        last_name: "vieira",
        title: "mr",
        picture: "men/59.jpg",
      },
      {
        email: "miguel.sanz@example.com",
        gender: "male",
        phone_number: "636-912-353",
        birthdate: 450524670,
        location: {
          street: "1543 calle de argumosa",
          city: "valladolid",
          state: "comunidad de madrid",
          postcode: 87843,
        },
        username: "silverfrog877",
        password: "gilligan",
        first_name: "miguel",
        last_name: "sanz",
        title: "mr",
        picture: "men/71.jpg",
      },
      {
        email: "karen.stanley@example.com",
        gender: "female",
        phone_number: "081-988-5646",
        birthdate: 1114669499,
        location: {
          street: "7483 dublin road",
          city: "loughrea",
          state: "illinois",
          postcode: 46508,
        },
        username: "heavyrabbit592",
        password: "virus",
        first_name: "karen",
        last_name: "stanley",
        title: "mrs",
        picture: "women/63.jpg",
      },
      {
        email: "tammy.hayes@example.com",
        gender: "female",
        phone_number: "081-647-6483",
        birthdate: 1178643060,
        location: {
          street: "2510 the grove",
          city: "athlone",
          state: "rhode island",
          postcode: 47861,
        },
        username: "brownrabbit758",
        password: "harley1",
        first_name: "tammy",
        last_name: "hayes",
        title: "ms",
        picture: "women/59.jpg",
      },
      {
        email: "شایان.حسینی@example.com",
        gender: "male",
        phone_number: "0946-021-2412",
        birthdate: 728429297,
        location: {
          street: "2818 میدان انقلاب",
          city: "ساوه",
          state: "لرستان",
          postcode: 61418,
        },
        username: "heavybird362",
        password: "instant",
        first_name: "شایان",
        last_name: "حسینی",
        title: "mr",
        picture: "men/58.jpg",
      },
      {
        email: "konrad.siebert@example.com",
        gender: "male",
        phone_number: "0176-8482149",
        birthdate: 563422602,
        location: {
          street: "1436 neue straße",
          city: "osterode am harz",
          state: "hessen",
          postcode: 42560,
        },
        username: "tinytiger768",
        password: "horny",
        first_name: "konrad",
        last_name: "siebert",
        title: "mr",
        picture: "men/45.jpg",
      },
      {
        email: "ben.perry@example.com",
        gender: "male",
        phone_number: "(412)-745-4263",
        birthdate: 189063593,
        location: {
          street: "5778 lakeshore rd",
          city: "west jordan",
          state: "ohio",
          postcode: 65378,
        },
        username: "smallfrog806",
        password: "01234567",
        first_name: "ben",
        last_name: "perry",
        title: "mr",
        picture: "men/77.jpg",
      },
      {
        email: "joaquin.hidalgo@example.com",
        gender: "male",
        phone_number: "614-654-138",
        birthdate: 1381390352,
        location: {
          street: "7830 calle de ángel garcía",
          city: "mérida",
          state: "comunidad valenciana",
          postcode: 88025,
        },
        username: "bigcat536",
        password: "kris",
        first_name: "joaquin",
        last_name: "hidalgo",
        title: "mr",
        picture: "men/57.jpg",
      },
      {
        email: "pauline.perez@example.com",
        gender: "female",
        phone_number: "(189)-609-2928",
        birthdate: 917729650,
        location: {
          street: "1493 rue de bonnel",
          city: "aclens",
          state: "valais",
          postcode: 8175,
        },
        username: "tinyfish934",
        password: "oicu812",
        first_name: "pauline",
        last_name: "perez",
        title: "madame",
        picture: "women/96.jpg",
      },
      {
        email: "tom.wolff@example.com",
        gender: "male",
        phone_number: "0175-3665364",
        birthdate: 477527796,
        location: {
          street: "6876 buchenweg",
          city: "vechta",
          state: "schleswig-holstein",
          postcode: 35491,
        },
        username: "ticklishduck355",
        password: "budlight",
        first_name: "tom",
        last_name: "wolff",
        title: "mr",
        picture: "algolia/men/xander.png",
      },
      {
        email: "oona.latvala@example.com",
        gender: "female",
        phone_number: "049-372-50-45",
        birthdate: 727804593,
        location: {
          street: "1534 tahmelantie",
          city: "vimpeli",
          state: "central ostrobothnia",
          postcode: 18173,
        },
        username: "purplelion119",
        password: "121212",
        first_name: "oona",
        last_name: "latvala",
        title: "miss",
        picture: "women/77.jpg",
      },
      {
        email: "james.lévesque@example.com",
        gender: "male",
        phone_number: "294-215-3722",
        birthdate: 808069609,
        location: {
          street: "5000 cedar st",
          city: "shelbourne",
          state: "yukon",
          postcode: 95160,
        },
        username: "bigelephant213",
        password: "hamish",
        first_name: "james",
        last_name: "lévesque",
        title: "mr",
        picture: "men/6.jpg",
      },
      {
        email: "femia.pruijssers@example.com",
        gender: "female",
        phone_number: "(328)-454-1571",
        birthdate: 725571465,
        location: {
          street: "5722 gansstraat",
          city: "ferwerderadiel",
          state: "gelderland",
          postcode: 28606,
        },
        username: "greenswan233",
        password: "grandpa",
        first_name: "femia",
        last_name: "pruijssers",
        title: "ms",
        picture: "women/11.jpg",
      },
      {
        email: "laly.dasilva@example.com",
        gender: "female",
        phone_number: "(082)-419-9335",
        birthdate: 1123776172,
        location: {
          street: "5396 rue duquesne",
          city: "villars-le-terroir",
          state: "ticino",
          postcode: 9152,
        },
        username: "bluebird274",
        password: "design",
        first_name: "laly",
        last_name: "da silva",
        title: "mademoiselle",
        picture: "women/9.jpg",
      },
      {
        email: "ross.nichols@example.com",
        gender: "male",
        phone_number: "081-438-6677",
        birthdate: 1110975010,
        location: {
          street: "6669 south street",
          city: "kilcock",
          state: "oklahoma",
          postcode: 75336,
        },
        username: "orangelion300",
        password: "blaze",
        first_name: "ross",
        last_name: "nichols",
        title: "mr",
        picture: "men/66.jpg",
      },
      {
        email: "sarah.oliver@example.com",
        gender: "female",
        phone_number: "0761-814-654",
        birthdate: 1038915780,
        location: {
          street: "3503 manor road",
          city: "manchester",
          state: "highlands and islands",
          postcode: "I30 5ZF",
        },
        username: "purplebear893",
        password: "boat",
        first_name: "sarah",
        last_name: "oliver",
        title: "ms",
        picture: "women/73.jpg",
      },
      {
        email: "jeanne.nelson@example.com",
        gender: "female",
        phone_number: "0418-190-097",
        birthdate: 591250973,
        location: {
          street: "1002 parker rd",
          city: "geelong",
          state: "northern territory",
          postcode: 3162,
        },
        username: "crazyladybug545",
        password: "313131",
        first_name: "jeanne",
        last_name: "nelson",
        title: "miss",
        picture: "women/33.jpg",
      },
      {
        email: "bernard.wilson@example.com",
        gender: "male",
        phone_number: "0727-970-211",
        birthdate: 504704897,
        location: {
          street: "9455 the drive",
          city: "preston",
          state: "cumbria",
          postcode: "A6N 9GS",
        },
        username: "smallduck339",
        password: "japanes",
        first_name: "bernard",
        last_name: "wilson",
        title: "mr",
        picture: "men/80.jpg",
      },
      {
        email: "darius.conrad@example.com",
        gender: "male",
        phone_number: "0171-7784156",
        birthdate: 12452416,
        location: {
          street: "7054 gartenweg",
          city: "osterode am harz",
          state: "bayern",
          postcode: 69450,
        },
        username: "smallgorilla954",
        password: "qwerqwer",
        first_name: "darius",
        last_name: "conrad",
        title: "mr",
        picture: "men/68.jpg",
      },
      {
        email: "malthe.andersen@example.com",
        gender: "male",
        phone_number: "12918640",
        birthdate: 722530420,
        location: {
          street: "1833 vestparken",
          city: "lemvig",
          state: "hovedstaden",
          postcode: 88997,
        },
        username: "crazyfish482",
        password: "junk",
        first_name: "malthe",
        last_name: "andersen",
        title: "mr",
        picture: "men/30.jpg",
      },
      {
        email: "emma.manni@example.com",
        gender: "female",
        phone_number: "043-835-10-98",
        birthdate: 458580461,
        location: {
          street: "6046 otavalankatu",
          city: "geta",
          state: "satakunta",
          postcode: 70518,
        },
        username: "tinymouse476",
        password: "tzpvaw",
        first_name: "emma",
        last_name: "manni",
        title: "miss",
        picture: "women/5.jpg",
      },
      {
        email: "druso.nascimento@example.com",
        gender: "male",
        phone_number: "(05) 2501-9070",
        birthdate: 845185612,
        location: {
          street: "5811 rua boa vista ",
          city: "vespasiano",
          state: "rio grande do norte",
          postcode: 74588,
        },
        username: "whitefish483",
        password: "goldstar",
        first_name: "druso",
        last_name: "nascimento",
        title: "mr",
        picture: "men/18.jpg",
      },
      {
        email: "greta.vanlimpt@example.com",
        gender: "female",
        phone_number: "(332)-879-4592",
        birthdate: 6714468,
        location: {
          street: "4062 wijde begijnestraat",
          city: "culemborg",
          state: "flevoland",
          postcode: 73952,
        },
        username: "smallduck854",
        password: "abcdefgh",
        first_name: "greta",
        last_name: "van limpt",
        title: "mrs",
        picture: "women/12.jpg",
      },
      {
        email: "نيما.جعفری@example.com",
        gender: "male",
        phone_number: "0912-030-9784",
        birthdate: 532295794,
        location: {
          street: "7577 میدان 7 تیر",
          city: "همدان",
          state: "اردبیل",
          postcode: 57685,
        },
        username: "beautifullion345",
        password: "insert",
        first_name: "نيما",
        last_name: "جعفری",
        title: "mr",
        picture: "men/42.jpg",
      },
      {
        email: "ستایش.یاسمی@example.com",
        gender: "female",
        phone_number: "0930-256-0917",
        birthdate: 1394744991,
        location: {
          street: "1897 هویزه",
          city: "بجنورد",
          state: "لرستان",
          postcode: 21321,
        },
        username: "silverostrich141",
        password: "kill",
        first_name: "ستایش",
        last_name: "یاسمی",
        title: "miss",
        picture: "women/10.jpg",
      },
      {
        email: "marcus.rasmussen@example.com",
        gender: "male",
        phone_number: "22688318",
        birthdate: 616133025,
        location: {
          street: "3776 frilandsvej",
          city: "gjerlev",
          state: "syddanmark",
          postcode: 36579,
        },
        username: "goldentiger886",
        password: "wayer",
        first_name: "marcus",
        last_name: "rasmussen",
        title: "mr",
        picture: "men/51.jpg",
      },
      {
        email: "peter.bell@example.com",
        gender: "male",
        phone_number: "0745-196-827",
        birthdate: 792581498,
        location: {
          street: "3477 the green",
          city: "ely",
          state: "lancashire",
          postcode: "SL7I 5TX",
        },
        username: "yellowladybug664",
        password: "dannyboy",
        first_name: "peter",
        last_name: "bell",
        title: "mr",
        picture: "men/53.jpg",
      },
      {
        email: "hector.guerrero@example.com",
        gender: "male",
        phone_number: "696-963-949",
        birthdate: 1040720948,
        location: {
          street: "5140 calle nebrija",
          city: "alcobendas",
          state: "navarra",
          postcode: 56387,
        },
        username: "lazyleopard999",
        password: "godfather",
        first_name: "hector",
        last_name: "guerrero",
        title: "mr",
        picture: "men/11.jpg",
      },
      {
        email: "arnaud.lo@example.com",
        gender: "male",
        phone_number: "905-307-4254",
        birthdate: 831874866,
        location: {
          street: "8252 20th ave",
          city: "maitland",
          state: "new brunswick",
          postcode: 16088,
        },
        username: "goldenwolf287",
        password: "dogfood",
        first_name: "arnaud",
        last_name: "lo",
        title: "mr",
        picture: "men/32.jpg",
      },
      {
        email: "julienne.lelieveld@example.com",
        gender: "female",
        phone_number: "(014)-370-6505",
        birthdate: 1132208385,
        location: {
          street: "4777 hoefsmederijpad",
          city: "leeuwarden",
          state: "zuid-holland",
          postcode: 27303,
        },
        username: "purpletiger354",
        password: "casey1",
        first_name: "julienne",
        last_name: "lelieveld",
        title: "mrs",
        picture: "women/86.jpg",
      },
      {
        email: "aurélien.fontai@example.com",
        gender: "male",
        phone_number: "(364)-916-4680",
        birthdate: 682846734,
        location: {
          street: "2443 place de la mairie",
          city: "epesses",
          state: "genève",
          postcode: 5403,
        },
        username: "silversnake816",
        password: "debra",
        first_name: "aurélien",
        last_name: "fontai",
        title: "monsieur",
        picture: "algolia/men/alexs.png",
      },
      {
        email: "valdemar.nielsen@example.com",
        gender: "male",
        phone_number: "10899723",
        birthdate: 95904272,
        location: {
          street: "5544 østervangsvej",
          city: "allinge",
          state: "syddanmark",
          postcode: 72707,
        },
        username: "bluegorilla239",
        password: "bluedog",
        first_name: "valdemar",
        last_name: "nielsen",
        title: "mr",
        picture: "men/99.jpg",
      },
      {
        email: "fabio.dupont@example.com",
        gender: "male",
        phone_number: "(503)-255-0533",
        birthdate: 1138394877,
        location: {
          street: "6321 avenue debourg",
          city: "denens",
          state: "neuchâtel",
          postcode: 9926,
        },
        username: "purplebear824",
        password: "shelly",
        first_name: "fabio",
        last_name: "dupont",
        title: "monsieur",
        picture: "men/1.jpg",
      },
      {
        email: "mathew.richards@example.com",
        gender: "male",
        phone_number: "0457-239-253",
        birthdate: 988778909,
        location: {
          street: "4290 lovers ln",
          city: "sunshine coast",
          state: "australian capital territory",
          postcode: 6869,
        },
        username: "blackpeacock624",
        password: "milo",
        first_name: "mathew",
        last_name: "richards",
        title: "mr",
        picture: "men/15.jpg",
      },
      {
        email: "nonato.pires@example.com",
        gender: "male",
        phone_number: "(62) 3725-1840",
        birthdate: 488254407,
        location: {
          street: "1697 rua tiradentes ",
          city: "são paulo",
          state: "roraima",
          postcode: 41957,
        },
        username: "redrabbit322",
        password: "phish",
        first_name: "nonato",
        last_name: "pires",
        title: "mr",
        picture: "men/91.jpg",
      },
      {
        email: "marjorie.steward@example.com",
        gender: "female",
        phone_number: "0446-772-290",
        birthdate: 1101314938,
        location: {
          street: "8735 bruce st",
          city: "traralgon",
          state: "south australia",
          postcode: 8028,
        },
        username: "brownlion891",
        password: "obsidian",
        first_name: "marjorie",
        last_name: "steward",
        title: "miss",
        picture: "women/36.jpg",
      },
      {
        email: "mia.sanchez@example.com",
        gender: "female",
        phone_number: "0729-610-908",
        birthdate: 324198991,
        location: {
          street: "7338 high street",
          city: "preston",
          state: "cleveland",
          postcode: "S16 2JE",
        },
        username: "whiteswan766",
        password: "again",
        first_name: "mia",
        last_name: "sanchez",
        title: "mrs",
        picture: "women/80.jpg",
      },
      {
        email: "efe.aydan@example.com",
        gender: "male",
        phone_number: "(360)-024-6328",
        birthdate: 748234079,
        location: {
          street: "7690 maçka cd",
          city: "artvin",
          state: "kırıkkale",
          postcode: 23645,
        },
        username: "ticklishlion559",
        password: "qwert",
        first_name: "efe",
        last_name: "aydan",
        title: "mr",
        picture: "men/62.jpg",
      },
      {
        email: "giselle.monteiro@example.com",
        gender: "female",
        phone_number: "(71) 5848-8742",
        birthdate: 1302716933,
        location: {
          street: "5474 rua piauí ",
          city: "americana",
          state: "rio grande do norte",
          postcode: 52659,
        },
        username: "blackgorilla346",
        password: "shou",
        first_name: "giselle",
        last_name: "monteiro",
        title: "miss",
        picture: "women/7.jpg",
      },
      {
        email: "theo.bader@example.com",
        gender: "male",
        phone_number: "0173-7423089",
        birthdate: 269358671,
        location: {
          street: "5774 gartenweg",
          city: "münster",
          state: "nordrhein-westfalen",
          postcode: 55289,
        },
        username: "orangetiger943",
        password: "blast",
        first_name: "theo",
        last_name: "bader",
        title: "mr",
        picture: "men/63.jpg",
      },
      {
        email: "cassandre.leroux@example.com",
        gender: "female",
        phone_number: "06-09-96-38-18",
        birthdate: 569521519,
        location: {
          street: "4917 rue duguesclin",
          city: "versailles",
          state: "territoire de belfort",
          postcode: 59655,
        },
        username: "bigwolf469",
        password: "spooge",
        first_name: "cassandre",
        last_name: "leroux",
        title: "mrs",
        picture: "women/25.jpg",
      },
      {
        email: "edgar.shelton@example.com",
        gender: "male",
        phone_number: "0467-658-105",
        birthdate: 125584897,
        location: {
          street: "4301 blossom hill rd",
          city: "warrnambool",
          state: "queensland",
          postcode: 2629,
        },
        username: "tinyswan868",
        password: "mmmm",
        first_name: "edgar",
        last_name: "shelton",
        title: "mr",
        picture: "men/46.jpg",
      },
      {
        email: "isabel.jackson@example.com",
        gender: "female",
        phone_number: "(570)-687-7371",
        birthdate: 1276278001,
        location: {
          street: "5749 main street west",
          city: "gisborne",
          state: "hawke's bay",
          postcode: 48884,
        },
        username: "blacksnake288",
        password: "corvette",
        first_name: "isabel",
        last_name: "jackson",
        title: "ms",
        picture: "women/30.jpg",
      },
      {
        email: "helena.wirth@example.com",
        gender: "female",
        phone_number: "0173-4867633",
        birthdate: 1060118652,
        location: {
          street: "9562 eichenweg",
          city: "traunstein",
          state: "rheinland-pfalz",
          postcode: 12847,
        },
        username: "heavybutterfly840",
        password: "panic",
        first_name: "helena",
        last_name: "wirth",
        title: "miss",
        picture: "women/53.jpg",
      },
      {
        email: "clotildes.darosa@example.com",
        gender: "female",
        phone_number: "(65) 9912-7496",
        birthdate: 469970647,
        location: {
          street: "9375 rua santa rita ",
          city: "itabira",
          state: "mato grosso do sul",
          postcode: 15517,
        },
        username: "bluegorilla991",
        password: "dank",
        first_name: "clotildes",
        last_name: "da rosa",
        title: "ms",
        picture: "women/16.jpg",
      },
      {
        email: "buse.dağdaş@example.com",
        gender: "female",
        phone_number: "(855)-841-4810",
        birthdate: 1316736697,
        location: {
          street: "6428 anafartalar cd",
          city: "malatya",
          state: "mardin",
          postcode: 28227,
        },
        username: "crazypeacock394",
        password: "paulie",
        first_name: "buse",
        last_name: "dağdaş",
        title: "ms",
        picture: "women/14.jpg",
      },
      {
        email: "amelia.mercier@example.com",
        gender: "female",
        phone_number: "(168)-747-5950",
        birthdate: 1132298571,
        location: {
          street: "7454 rue duquesne",
          city: "echandens-denges",
          state: "vaud",
          postcode: 3811,
        },
        username: "whitefrog218",
        password: "forest",
        first_name: "amelia",
        last_name: "mercier",
        title: "madame",
        picture: "women/91.jpg",
      },
      {
        email: "maureen.ramos@example.com",
        gender: "female",
        phone_number: "0486-809-748",
        birthdate: 697348911,
        location: {
          street: "4236 adams st",
          city: "coffs harbour",
          state: "tasmania",
          postcode: 9392,
        },
        username: "purplepeacock730",
        password: "blabla",
        first_name: "maureen",
        last_name: "ramos",
        title: "miss",
        picture: "women/69.jpg",
      },
      {
        email: "solène.lemaire@example.com",
        gender: "female",
        phone_number: "06-41-57-50-80",
        birthdate: 756942823,
        location: {
          street: "8259 rue paul-duvivier",
          city: "metz",
          state: "vendée",
          postcode: 96673,
        },
        username: "heavyladybug601",
        password: "harold",
        first_name: "solène",
        last_name: "lemaire",
        title: "mrs",
        picture: "women/76.jpg",
      },
      {
        email: "ernest.williamson@example.com",
        gender: "male",
        phone_number: "081-571-7090",
        birthdate: 439547391,
        location: {
          street: "7184 main street",
          city: "tramore",
          state: "maine",
          postcode: 10605,
        },
        username: "silverleopard819",
        password: "2112",
        first_name: "ernest",
        last_name: "williamson",
        title: "mr",
        picture: "algolia/men/tim.png",
      },
      {
        email: "florian.hahn@example.com",
        gender: "male",
        phone_number: "0170-0421455",
        birthdate: 25757437,
        location: {
          street: "6870 birkenstraße",
          city: "ostprignitz-ruppin",
          state: "sachsen",
          postcode: 97964,
        },
        username: "smallsnake648",
        password: "iron",
        first_name: "florian",
        last_name: "hahn",
        title: "mr",
        picture: "algolia/men/julien.png",
      },
      {
        email: "jalisa.köhler@example.com",
        gender: "female",
        phone_number: "(462)-622-9092",
        birthdate: 1052886108,
        location: {
          street: "1555 maliebaan",
          city: "leiden",
          state: "limburg",
          postcode: 61896,
        },
        username: "greenelephant861",
        password: "joker1",
        first_name: "jalisa",
        last_name: "köhler",
        title: "mrs",
        picture: "women/27.jpg",
      },
    ],
  });
});

module.exports = router;
